export const ROUTES = {
    HOME: '/',
    CONTACT: '/contact',
    LOGIN: '/login',
    USER: '/user',
    ADMIN: '/admin',
    ANIMAL: '/animal/:id',
    DIAGNOSTIC: '/animal/:id/diagnostic', 
    ANALYSIS: '/animal/:id/analysis', 
    VACCINATION: '/animal/:id/vaccination',
    REGISTER: '/admin/register',
    EDIT: '/admin/edit/:id',
    NEWANIMAL: '/admin/newAnimal/:id',
    USERANIM: '/admin/user/:id/animals',
    CONSULTATION: '/admin/animal/:id/consultation',
    DIAGNOSTICNEW: '/admin/animal/:id/diagnostic/new',
    ANALYSISNEW: '/admin/animal/:id/analysis/new',
    VACCINATIONNEW: '/admin/animal/:id/vaccination/new',
    HISTORY: '/admin/animal/:id/history',
    APPOINTMENT: '/admin/appointments',
}