version: '3.8'

services:
  backend:
    build: ./backend
    container_name: qivet_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/public:/usr/src/public
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=qivet_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - JWT_SECRET=tu_secreto_jwt_seguro
      - ADMIN_EMAIL=admin@qivet.com
      - ADMIN_PASSWORD=admin
      - ADMIN_NAME=Qivet
      - ADMIN_LASTNAME=Admin
      - ADMIN_PHONE="1234567890"
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qivet_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api/
    networks:
      - backend_network
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:latest
    container_name: qivet_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qivet_db
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d qivet_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge