version: '3.8'

services:
  backend:
    build: ./backend
    container_name: qivet_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src/public:/usr/src/public
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=qivet_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - JWT_SECRET=tu_secreto_jwt_seguro
      - ADMIN_EMAIL=admin@qivet.com
      - ADMIN_PASSWORD=admin
      - ADMIN_NAME=Qivet
      - ADMIN_LASTNAME=Admin
      - ADMIN_PHONE="1234567890"
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qivet_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api/
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend_network
    depends_on:
      - backend
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    container_name: qivet_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qivet_db
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d qivet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: qivet_pgweb
    ports:
      - "8080:8081"
    environment:
      - PGWEB_DB=postgres://admin:admin@postgres:5432/qivet_db?sslmode=disable
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge