version: '3.8'
services:
  backend:
    build: .
    container_name: qivet_backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./public/images:/app/public/images
      - ./public/pdfs:/app/public/pdfs
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=qivet_db
      - DB_USER=admin
      - DB_PASSWORD=admin
    networks:
      - backend_network
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: qivet_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: qivet_db
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d qivet_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  pgweb:
    image: sosedoff/pgweb
    container_name: qivet_pgweb
    ports:
      - "8080:8081"
    environment:
      - PGWEB_DB=postgres://admin:admin@postgres:5432/qivet_db?sslmode=disable
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
